[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
async-std = { version = "1.13.1", features = ["attributes"]}
tokio = { version = "1.44.2", features = ["full"] }
tokio-tungstenite = "0.20.1"
futures-util = "0.3.31"
futures = "0.3.31"

